bitverse_identicon:
    preprocessor:
        class: Bitverse\Identicon\Preprocessor\MD5Preprocessor
    generator:
        class: Bitverse\Identicon\Generator\PixelsGenerator

services:
    bitverse.identicon.preprocessor:
        class: %bitverse_identicon.preprocessor.class%
        public: false

    bitverse.identicon.generator:
        class: %bitverse_identicon.generator.class%
        public: false

    bitverse.identicon:
        class: Bitverse\Identicon\Identicon
        args: ["@bitverse.identicon.preprocessor", "@bitverse.identicon.generator"]

    identicon:
        alias: bitverse.identicon
